//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsommationCarburant
    {
        public int ID_ConsommationCarburant { get; set; }
        public string Immatricule { get; set; }
        public decimal VolumeGasoil { get; set; }
        public decimal PrixBon { get; set; }
        public Nullable<System.DateTime> DateRemplissage { get; set; }
        public int Kilometrage { get; set; }
    
        public virtual Vehicule Vehicule { get; set; }
    }
}
