//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_ProjectEleEntities : DbContext
    {
        public db_ProjectEleEntities()
            : base("name=db_ProjectEleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConsommationCarburant> ConsommationCarburants { get; set; }
        public virtual DbSet<Ouvrier> Ouvriers { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Pylone> Pylones { get; set; }
        public virtual DbSet<Repos> Repos { get; set; }
        public virtual DbSet<Travaux> Travauxes { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
    }
}
