//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrier()
        {
            this.Paiements = new HashSet<Paiement>();
            this.Repos = new HashSet<Repos>();
            this.Travauxes = new HashSet<Travaux>();
        }
    
        public string CIN { get; set; }
        public string NomComplet { get; set; }
        public string Ville { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<System.DateTime> DateDebutActivite { get; set; }
        public string fonction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paiement> Paiements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repos> Repos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travaux> Travauxes { get; set; }
    }
}
