//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int ID_Paiements { get; set; }
        public string CIN { get; set; }
        public Nullable<System.DateTime> Mois { get; set; }
        public decimal Montant { get; set; }
    
        public virtual Ouvrier Ouvrier { get; set; }
    }
}
