//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pylone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pylone()
        {
            this.Travauxes = new HashSet<Travaux>();
        }
    
        public int NumeroPylone { get; set; }
        public string LigneElectrique { get; set; }
        public string Ville { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public string EtatDegradation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travaux> Travauxes { get; set; }
    }
}
