//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repos
    {
        public int ID_Repos { get; set; }
        public string CIN { get; set; }
        public System.DateTime DateRepos { get; set; }
        public string MotifRepos { get; set; }
    
        public virtual Ouvrier Ouvrier { get; set; }
    }
}
