//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinalVersio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travaux
    {
        public int ID_Travaux { get; set; }
        public int NumeroPylone { get; set; }
        public string CIN { get; set; }
        public Nullable<System.DateTime> DateTravail { get; set; }
        public decimal TauxAvancement { get; set; }
    
        public virtual Ouvrier Ouvrier { get; set; }
        public virtual Pylone Pylone { get; set; }
    }
}
